services:
  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"

    ports:
      - "9201:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
    name: elastic



#  7dqftZxCS=yiyhFuZrqF
    #        - "discovery.type=single-node"
    #        - "xpack.security.transport.ssl.enabled=false"